### ISSUE TITLE
Increase the number of forum subscriptions

### ISSUE THREAD

**Issue by qazip** [aaroncox/chainbb-frontend#3]
As it is, we can only subscribe to 3 forums, right? It would be nice if one could subscribe to as many forums as one wants.

**Comment by qazip** [comment]
Ah wait. it seems you can subscribe to more than 3 forums, however, the behaviour is a bit weird when you do it in different tabs. Try the following:

- Open 3 different chainBB's forums in different tabs;
- Subscribe to one forum/tab, close that tab;
- Subscribe to another forum/tab, and refresh;

Now, if you open chainBB again, you should be able to see that you're subscribed to 2 forums. That's not what happens. You're only subcribed to one.

**Comment by aaroncox** [comment]
Sorry I never responded to this one. I do want to resolve the issues with subscriptions being out of sync between tabs - which is part of the larger overhaul in aaroncox/chainbb#52.
